### ISSUE TITLE
如何获取网页登陆B站的cookie呢

### ISSUE THREAD

**Issue by lsylusiyao** [MoyuScript/double-mouse-downloader#15]
我想直接从网页端登陆后的账号获取cookie然后在软件中登陆，应该怎么获取这个cookie呢？

**Comment by y-Soserious** [comment]
登录了的页面，F12调出开发者工具，随便查看一条请求，cookie中的值全部复制，粘贴到客户端皆可。

![image](https://user-images.githubusercontent.com/32934247/192132041-2d6821f5-cde3-491e-8a0d-5c9c9e6a7b45.png)

**Comment by lsylusiyao** [comment]
谢谢，已成功登陆。
